### ISSUE TITLE
Bring! 

### ISSUE THREAD

**Issue by thetobyde** [lavolp3/MMM-Keyboard#4]
Hey mate! Nice Keyboard! 
It works with MMM-Bring. If I want to add a new Item to my shipping List the Keyboard is appearing nicely. But when I enter my text and "send" it, the keyboard disappears, as I want to but in my Bring! Shipping List there is no new Item. What am I doing wrong?
Thx 4 help bro 👍 
Toby

**Comment by lavolp3** [comment]
Oh boy. I need to check that. So everything works as expected but the new item does not appear? 
Can you set
```
debug: true
```
in your mmm-keyboard config entry and check the browser dev console (Press F12 in browser) for the entries of the module?

**Comment by thetobyde** [comment]
Thx for the fast response. 
I think the Bring module doas not get the Keyboard Input, cause the Keyboard sends the input perfect. See this:

![image0](https://user-images.githubusercontent.com/53558782/89015780-e9e48e80-d317-11ea-9896-040c8857dc33.jpeg)

**Comment by lavolp3** [comment]
ok thank you mate for finding this small but important bug. The keyword sent by MMM-Bring (key: "mmm-bring") has not been consistent with the key that mmm-bring filters for again. (if key === "bring"). The notification has never been interpreted.
Sent a PR to MMM-Bring which hopefully gets merged soon. 
See https://github.com/werthdavid/MMM-Bring/pull/16
Let me know if it works then.
